INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 25, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 15, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 10);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 5, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 35, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 45, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 50);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 20, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 12, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 22);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 8, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 38, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 18, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 27);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 19, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 14, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 20);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 11, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 36, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 22, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 33);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 21, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 16, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 9, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 42, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 24, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 35);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 17, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 24);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 13, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 37, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 29, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 39);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 22, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 19, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 25);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 15, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 34, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 21, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 23, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 17, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 26);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 14, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 41, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 25, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 36);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 24, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 23);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 12, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 39, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 20, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 30);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 25, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 15, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 10);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 5, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 35, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 45, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 50);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 20, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 12, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 22);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 8, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 38, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 18, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 27);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 19, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 14, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 20);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 11, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 36, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 22, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 33);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 21, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 16, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 9, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 42, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 24, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 35);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 17, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 24);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 13, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 37, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 29, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 39);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 22, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 19, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 25);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 15, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 34, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 21, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 23, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 17, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 26);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 14, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 41, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 25, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 36);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 24, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 23);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 12, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 39, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 20, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 30);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 25, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 15, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 10);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 5, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 35, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 45, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 50);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 20, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 12, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 22);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 8, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 38, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 18, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 27);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 19, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 14, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 20);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 11, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 36, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 22, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 33);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 21, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 16, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 9, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 42, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 24, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 35);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 17, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 24);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 13, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 37, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 29, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 39);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 22, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 19, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 25);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 15, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 34, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 21, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 23, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 17, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 26);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 14, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 41, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 25, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 36);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 24, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 23);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 12, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 39, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 20, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 30);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 25, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 15, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 10);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 5, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 35, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 45, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 50);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 20, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 12, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 22);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 8, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 38, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 18, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 27);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 19, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 14, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 20);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 11, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 36, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 22, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 33);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 21, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 16, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 9, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 42, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 24, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 35);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 17, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 24);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 13, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 37, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 29, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 39);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 22, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 19, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 25);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 15, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 34, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 21, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 28);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 23, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 17, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 26);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 14, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 41, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 25, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 36);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 24, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 18, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 23);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 12, 'JPY');
