USE expenses;

INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2500, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1500, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 1000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 500, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3500, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 4500, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 5000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2000, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1200, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2200);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 800, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3800, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 1800, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 2700);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 1900, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1400, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1100, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3600, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2200, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3300);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2100, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1600, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2800);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 900, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 4200, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2400, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3500);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 1700, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1800, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2400);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1300, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3700, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2900, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3900);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2200, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1900, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2500);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1500, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3400, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2100, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 2800);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2300, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1700, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2600);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1400, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 4100, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2500, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3600);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2400, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1800, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2300);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1200, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3900, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2000, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2500, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1500, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 1000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 500, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3500, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 4500, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 5000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2000, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1200, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2200);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 800, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3800, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 1800, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 2700);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 1900, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1400, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1100, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3600, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2200, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3300);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2100, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1600, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2800);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 900, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 4200, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2400, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3500);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 1700, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1800, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2400);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1300, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3700, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2900, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3900);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2200, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1900, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2500);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1500, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3400, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2100, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 2800);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2300, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1700, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2600);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1400, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 4100, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2500, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3600);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2400, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1800, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 2300);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 1200, 'JPY');
INSERT INTO expenses (title, description, amount, currency) VALUES ('śniadanie', 'zakupy na śniadanie', 3900, 'PLN');
INSERT INTO expenses (title, description, amount, currency) VALUES ('obiad', 'zakupy na obiad', 2000, 'USD');
INSERT INTO expenses (title, description, amount) VALUES ('kolacja', 'zakupy na kolację', 3000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('lunch', 'zakupy na lunch', 2500, 'EUR');
INSERT INTO expenses (title, description, amount, currency) VALUES ('przekąska', 'zakupy na przekąski', 1500, 'GBP');
INSERT INTO expenses (title, description, amount) VALUES ('deser', 'zakupy na deser', 1000);
INSERT INTO expenses (title, description, amount, currency) VALUES ('napój', 'zakupy na napoje', 500, 'JPY');
