INSERT INTO categories (name, description) VALUES ('Groceries', 'Expenses related to food and household supplies');
INSERT INTO categories (name, description) VALUES ('Rent', 'Monthly housing rent payments');
INSERT INTO categories (name, description) VALUES ('Utilities', 'Payments for electricity, water, gas, etc.');
INSERT INTO categories (name, description) VALUES ('Transportation', 'Expenses for public transport or vehicle maintenance');
INSERT INTO categories (name, description) VALUES ('Healthcare', 'Medical and healthcare-related expenses');
INSERT INTO categories (name, description) VALUES ('Education', 'Expenses for tuition and educational materials');
INSERT INTO categories (name, description) VALUES ('Insurance', 'Premiums for health, auto, home insurance, etc.');
INSERT INTO categories (name, description) VALUES ('Entertainment', 'Expenses for movies, concerts, and other leisure activities');
INSERT INTO categories (name, description) VALUES ('Dining Out', 'Meals and drinks at restaurants and cafes');
INSERT INTO categories (name, description) VALUES ('Travel', 'Expenses related to travel and vacations');
INSERT INTO categories (name, description) VALUES ('Clothing', 'Purchase of clothing and accessories');
INSERT INTO categories (name, description) VALUES ('Savings', 'Money set aside for savings or investments');
INSERT INTO categories (name, description) VALUES ('Gifts', 'Purchases made for gifts to others');
INSERT INTO categories (name, description) VALUES ('Charity', 'Donations to charitable organizations');
INSERT INTO categories (name, description) VALUES ('Childcare', 'Expenses for childcare services and supplies');
INSERT INTO categories (name, description) VALUES ('Pets', 'Expenses related to pet care and supplies');
INSERT INTO categories (name, description) VALUES ('Home Improvement', 'Costs for repairs and improvements to the home');
INSERT INTO categories (name, description) VALUES ('Subscriptions', 'Recurring subscriptions to services and products');
INSERT INTO categories (name, description) VALUES ('Books', 'Purchase of books and reading materials');
INSERT INTO categories (name, description) VALUES ('Electronics', 'Expenses for electronic gadgets and devices');
INSERT INTO categories (name, description) VALUES ('Hobbies', 'Expenses related to personal hobbies and interests');
INSERT INTO categories (name, description) VALUES ('Fitness', 'Memberships and fees for gyms and fitness classes');
INSERT INTO categories (name, description) VALUES ('Personal Care', 'Expenses for cosmetics, grooming, and personal care');
INSERT INTO categories (name, description) VALUES ('Debt Repayment', 'Payments towards loans and credit card debt');
INSERT INTO categories (name, description) VALUES ('Household Services', 'Expenses for cleaning, gardening, etc.');
INSERT INTO categories (name, description) VALUES ('Legal Fees', 'Payments for legal advice and services');
INSERT INTO categories (name, description) VALUES ('Taxes', 'Payments for various local and federal taxes');
INSERT INTO categories (name, description) VALUES ('Miscellaneous', 'Other uncategorized expenses');
INSERT INTO categories (name, description) VALUES ('Investment', 'Purchases of stocks, bonds, and other investment vehicles');
INSERT INTO categories (name, description) VALUES ('Furniture', 'Expenses for buying furniture and home decor');
